//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringToNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringToNumber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND|&amp;.
        /// </summary>
        internal static string AndWords {
            get {
                return ResourceManager.GetString("AndWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNDRED:100|THOUSAND:1000|MILLION:1000000|MILLIARD:1000000000|BILLION:1000000000000|BILLIARD:1000000000000000|TRILLION:1000000000000000000|TRILLIARD:1000000000000000000000|QUADRILLION:1000000000000000000000000.
        /// </summary>
        internal static string LongScaleGroups {
            get {
                return ResourceManager.GetString("LongScaleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWENTY:20|20:20|THIRTY:30|30:30|FOURTY:40|40:40|FIFTY:50|50:50|SIXTY:60|60:60|SEVENTY:70|70:70|EIGHTY:80|80:80|NINETY:90|90:90.
        /// </summary>
        internal static string MotWordsAndValues {
            get {
                return ResourceManager.GetString("MotWordsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUS|NEGATIVE.
        /// </summary>
        internal static string NegativeWords {
            get {
                return ResourceManager.GetString("NegativeWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNDRED:100|THOUSAND:1000|MILLION:1000000|BILLION:1000000000|TRILLION:1000000000000|QUADRILLION:1000000000000000|QUINTILLION:1000000000000000000|SEXTILLION:1000000000000000000000|SEPTILLION:1000000000000000000000000|OCTILLION:1000000000000000000000000000.
        /// </summary>
        internal static string ShortScaleGroups {
            get {
                return ResourceManager.GetString("ShortScaleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A|AN.
        /// </summary>
        internal static string SingleWords {
            get {
                return ResourceManager.GetString("SingleWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  |,|-|..
        /// </summary>
        internal static string SplitterChars {
            get {
                return ResourceManager.GetString("SplitterChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEN:10|10:10|ELEVEN:11|11:11|TWELVE:12|12:12|THIRTEEN:13|13:13|FOURTEEN:14|14:14|FIFTEEN:15|15:15|SIXTEEN:16|16:16|SEVENTEEN:17|17:17|EIGHTEEN:18|18:18|NINETEEN:19|19:19.
        /// </summary>
        internal static string TeenWordsAndValues {
            get {
                return ResourceManager.GetString("TeenWordsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE:1|1:1|TWO:2|2:2|THREE:3|3:3|FOUR:4|4:4|FIVE:5|5:5|SIX:6|6:6|SEVEN:7|7:7|EIGHT:8|8:8|NINE:9|9:9.
        /// </summary>
        internal static string UnitWordsAndValues {
            get {
                return ResourceManager.GetString("UnitWordsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZERO|NONE|0|O.
        /// </summary>
        internal static string ZeroWords {
            get {
                return ResourceManager.GetString("ZeroWords", resourceCulture);
            }
        }
    }
}
